### ISSUE TITLE
on_wake_word_detected

### ISSUE THREAD

**Issue by lordbah** [esphome/firmware#127]
Can there be an on_wake_word_detected trigger in voice-assistant/m5stack-atom-echo.yaml we can use to call HA services to pause other speakers/TVs/etc.? I would also call sonos.snapshot.

**Comment by timmo001** [comment]
You could probably just trigger from the assist in progress binary sensor:

![image](https://github.com/esphome/firmware/assets/28114703/db26363c-afc3-4e39-bae5-1373668c50c6)

**Comment by jesserockz** [comment]
You can add this trigger in your adopted yaml to do what you want with it, such as service calls etc.
