### ISSUE TITLE
wake-word-voice-assistant/m5stack-atom-echo.yaml is a lie

### ISSUE THREAD

**Issue by brettmiller** [esphome/firmware#180]
The `wake-word-voice-assistant/m5stack-atom-echo.yaml` file doesn't enable micro-wake-word support like the yaml files for the other devices in the `wake-work-voice-assistant/` directory. It instead just contains a package reference to `github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main` without micro-wake-word support.

After having micro-wake-word work great on an esp32-s3-box I attempted to enable on an atom-echo with the above mentioned file. The option for "Wake word engine location" didn't exist and investigation showed was really just using the original yaml in `voice-assistant/m5stack-atom-echo.yaml`. The "fake" addition was done in #167 and seems like it could cause others confusion as well.

**Comment by Evanito** [comment]
Implementation is complete now and this is no longer the case. Suggest closing
