### ISSUE TITLE
ESP32 S3 Box can't be updated

### ISSUE THREAD

**Issue by ChristophCaina** [esphome/firmware#206]
I've seen, that there's already an OTA fix available for the VoiceAssistant Firmware - but somehow, the S3-Box still can't be updated...

I am getting the following error:
![grafik](https://github.com/esphome/firmware/assets/26391061/a3501ccd-fd5a-41fe-b468-0491300eca54)

**Comment by WarC0zes** [comment]
Hi,
add in your code:
```
ota:
  - platform: esphome
```
despite declaring the package, it does not add the OTA configuration. I had to add it to the ESP code to be able to compile otherwise I got an error.

**Comment by ChristophCaina** [comment]
I've tried this with 2024.6.0
Since 2024.6.1 this hast been added to the Firmware, but the Box ist still Not getting the Update. 

For all other devices, adding the Plattform was working.

**Comment by ChristophCaina** [comment]
it seems that this is due to the "micro_wake_word_model" in the substitutions...
If I remove this from the configuration, compiling / uploading the new firmware is working as expected.
