### ISSUE TITLE
Cannot adopt ESP32-C3 esphome-web

### ISSUE THREAD

**Issue by jamesmyatt** [esphome/firmware#208]
I am unable to adopt an ESP32-C3 device flashed with the default empty esphome firmware on 2024.6.1 from https://web.esphome.io/.

```
INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/esphome-web-3766c8.yaml...
Failed config

At least one platform must be specified for 'ota'; add 'platform: esphome' for original OTA functionality
```

**Comment by randybb** [comment]
There was a breaking change in this release - read release notes and fix your config accordingly https://esphome.io/changelog/2024.6.0.html#ota-platforms

**Comment by jamesmyatt** [comment]
I'm aware of that. But the config it's adopting when ought to work without modification.
