### ISSUE TITLE
Ready Made Projects - BT Proxy "Failed to download manifest"

### ISSUE THREAD

**Issue by hamsando** [esphome/firmware#255]
Attempting to go with a "Ready Made Project" from "https://esphome.io/projects/" - specifically, "Bluetooth Proxy" fails immediately with: "Failed to download manifest" immediately after connecting to the COM port.

This worked a couple of days ago. It seems that it is attempting to download:

https://firmware.esphome.io/bluetooth-proxy/olimex-esp32-poe-iso/manifest.json

but that file doesn't exist.

**Comment by mhalano** [comment]
I also have this problem, but with the page https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

**Comment by Darkangeel-hd** [comment]
> Attempting to go with a "Ready Made Project" from "https://esphome.io/projects/" - specifically, "Bluetooth Proxy" fails immediately with: "Failed to download manifest" immediately after connecting to the COM port.
> 
> This worked a couple of days ago. It seems that it is attempting to download:
> 
> https://firmware.esphome.io/bluetooth-proxy/olimex-esp32-poe-iso/manifest.json
> 
> but that file doesn't exist.

This one should be fixed by esphome/bluetooth-proxies#97
