### ISSUE TITLE
Feature Request:  Leverage the ESP32-S3-Box3's bluetooth capabilities to pair with a bluetooth speaker

### ISSUE THREAD

**Issue by FrankJaco** [esphome/firmware#260]
We all know the problem.... The ESP32-S3-Box3 works quite well... The microphones work well, the screen response is decent. Great little voice assistant EXCEPT for the dismal volume and audio quality. Many of us have tried workarounds such as redirecting the output to an available media player, or modifying the hardware to connect the speaker output to a external amp and speaker.  Each of these workarounds do solve the audio quality/volume issue but present new problems of their own or are plain ugly.

Why not leverage the ESP32-S3-Box3 bluetooth capabilities so that you could simply pair the device with a typical bluetooth speaker? 

No hardware monkeying around except maybe to disconnect the connector for the internal speaker.  No complex yaml to adjust media player volume, save its current state and then attempt to start it all again after the assist session is complete. Also those occasional false positives that interrupt your media goes away. etc. etc.   It seem to me that simply redirecting the audio of the voice assistant to a bluetooth speaker would solve all these problems.

But is it doable?

fj

**Comment by jesserockz** [comment]
ESPHome does not support classic bluetooth/audio. 

This will not be done in the near future unless somebody contributes it so I am going to close this FR.

Jesse
