### ISSUE TITLE
SC01 Plus Support

### ISSUE THREAD

**Issue by broyuken** [esphome/firmware#64]
Does this firmware work on the S3 SC01 Plus?

SC01 Plus Development Board with 3.5'' 320x480 Color Touch Screen LCD Display, Based on ESP32-S3, Wi-Fi, Bluetooth Connection for Bicycle Computer Meters,Air Fryers, Water Heaters, Washing Machines https://a.co/d/57YkBCe

**Comment by jesserockz** [comment]
This is not the right place to ask this. Issues created here should only be about the current YAML configuration files present in the repository.
