### ISSUE TITLE
ESP32 s3 box - lite No WIFI prompt after install 

### ISSUE THREAD

**Issue by MathewJH1** [esphome/firmware#68]
Completed the install process via ESPHome, ESP s3 Box Lite  no prompt to setup WIFI after install

YAML I am using

---
esphome:
  name: esp32-s3-box-lite
  friendly_name: ESP32 S3 Box Lite
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: esphome.voice-assistant
    version: "1.0"
  min_version: 2023.10.0b1
  on_boot:
    - priority: -100
      then:
        - wait_until: api.connected
        - delay: 1s
        - if:
            condition:
              switch.is_on: use_wake_word
            then:
              - voice_assistant.start_continuous:

esp32:
  board: esp32s3box
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

api:
ota:
logger:
  hardware_uart: USB_SERIAL_JTAG
  logs:
    sensor: INFO

dashboard_import:
  package_import_url: github://esphome/firmware/voice-assistant/esp32-s3-box-lite.yaml@main

wifi:
  ap:

sensor:
  - platform: adc
    pin: GPIO1
    id: front_buttons
    update_interval: 16ms
    attenuation: 11db
    on_value:
      - lambda: |-
          // none: 3.121
          // left: 2.392
          // middle: 1.965
          // left+middle: 1.600
          // right: 0.794
          // left+right: 0.726
          // middle+right: 0.682
          // all: 0.632
          if (x > 3) {
            id(left).publish_state(false);
            id(middle).publish_state(false);
            id(right).publish_state(false);
          } else if (x > 2.3) {
            id(left).publish_state(true);
            id(middle).publish_state(false);
            id(right).publish_state(false);
          } else if (x > 1.9) {
            id(left).publish_state(false);
            id(middle).publish_state(true);
            id(right).publish_state(false);
          } else if (x > 1) {
            id(left).publish_state(true);
            id(middle).publish_state(true);
            id(right).publish_state(false);
          } else if (x > 0.73) {
            id(left).publish_state(false);
            id(middle).publish_state(false);
            id(right).publish_state(true);
          } else if (x > 0.7) {
            id(left).publish_state(true);
            id(middle).publish_state(false);
            id(right).publish_state(true);
          } else if (x > 0.65) {
            id(left).publish_state(false);
            id(middle).publish_state(true);
            id(right).publish_state(true);
          } else {
            id(left).publish_state(true);
            id(middle).publish_state(true);
            id(right).publish_state(true);
          }
binary_sensor:
  - platform: template
    id: left
    name: "Left"
  - platform: template
    id: middle
    name: "Middle"
  - platform: template
    id: right
    name: "Right"

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: Left Top Button
    disabled_by_default: true
    on_click:
      - if:
          condition:
            switch.is_off: use_wake_word
          then:
            - if:
                condition: voice_assistant.is_running
                then:
                  - voice_assistant.stop:
                  - script.execute: reset_led
                else:
                  - voice_assistant.start:
          else:
            - voice_assistant.stop
            - delay: 1s
            - script.execute: reset_led
            - script.wait: reset_led
            - voice_assistant.start_continuous:

output:
  - platform: ledc
    pin: GPIO45
    inverted: true
    id: backlight_output

light:
  - platform: monochromatic
    output: backlight_output
    name: LCD Backlight
    id: led
    restore_mode: ALWAYS_OFF
    disabled_by_default: true
    default_transition_length: 0s
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms

esp_adf:
  board: esp32s3boxlite

microphone:
  - platform: esp_adf
    id: box_mic

speaker:
  - platform: esp_adf
    id: box_speaker

voice_assistant:
  id: va
  microphone: box_mic
  speaker: box_speaker
  use_wake_word: true
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  vad_threshold: 3
  on_listening:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 100%
        effect: pulse
  on_tts_start:
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        brightness: 100%
        effect: pulse
  on_end:
    - delay: 100ms
    - wait_until:
        not:
          speaker.is_playing:
    - script.execute: reset_led
  on_error:
    - light.turn_on:
        id: led
        blue: 0%
        red: 100%
        green: 0%
        brightness: 100%
        effect: none
    - delay: 1s
    - script.execute: reset_led
    - script.wait: reset_led
    - lambda: |-
        if (code == "wake-provider-missing" || code == "wake-engine-missing") {
          id(use_wake_word).turn_off();
        }

script:
  - id: reset_led
    then:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - light.turn_on:
                id: led
                blue: 100%
                red: 100%
                green: 0%
                brightness: 100%
                effect: none
          else:
            - light.turn_off: led

switch:
  - platform: template
    name: Use wake word
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - lambda: id(va).set_use_wake_word(true);
      - if:
          condition:
            not:
              - voice_assistant.is_running
          then:
            - voice_assistant.start_continuous
      - script.execute: reset_led
    on_turn_off:
      - voice_assistant.stop
      - lambda: id(va).set_use_wake_word(false);
      - script.execute: reset_led

external_components:
  - source: github://pr#5230
    components: esp_adf
    refresh: 0s

psram:
  mode: octal
  speed: 80MHz

**Comment by MathewJH1** [comment]
Log files from esp

ESP-ROM:esp32s3-20210327
[D][binary_sensor:036]: 'Left Top Button': Sending state ON
[D][binary_sensor:036]: 'Left Top Button': Sending state OFF
[W][light:176]: 'LCD Backlight' - This color mode does not support setting RGB color!
[D][light:036]: 'LCD Backlight' Setting:
[D][light:051]:   Brightness: 100%
[E][voice_assistant:412]: No API client connected
[D][voice_assistant:366]: State changed from IDLE to IDLE
[D][voice_assistant:372]: Desired state set to IDLE
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x2b (SPI_FAST_FLASH_BOOT)
Saved PC:0x420b7c6a
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x162c
load:0x403c9700,len:0xbb8
load:0x403cc700,len:0x2f2c
entry 0x403c9950
I (24) boot: ESP-IDF 4.4.5 2nd stage bootloader
I (25) boot: compile time 19:44:55
I (25) boot: chip revision: v0.1
I (26) boot.esp32s3: Boot SPI Speed : 80MHz
I (31) boot.esp32s3: SPI Mode       : DIO
I (36) boot.esp32s3: SPI Flash Size : 16MB
I (41) boot: Enabling RNG early entropy source...
I (46) boot: Partition Table:
I (50) boot: ## Label            Usage          Type ST Offset   Length
I (57) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (64) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (72) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (79) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (87) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (94) boot: End of partition table
I (99) esp_image: segment 0: paddr=00010020 vaddr=3c0c0020 size=2de58h (187992) map
I (141) esp_image: segment 1: paddr=0003de80 vaddr=3fc97240 size=02198h (  8600) load
I (143) esp_image: segment 2: paddr=00040020 vaddr=42000020 size=bdb38h (777016) map
I (286) esp_image: segment 3: paddr=000fdb60 vaddr=3fc993d8 size=01f7ch (  8060) load
I (288) esp_image: segment 4: paddr=000ffae4 vaddr=40374000 size=13238h ( 78392) load
I (316) boot: Loaded app from partition at offset 0x10000
I (317) boot: Disabling RNG early entropy source...
I (318) opi psram: vendor id : 0x0d (AP)
I (321) opi psram: dev id    : 0x02 (generation 3)
I (327) opi psram: density   : 0x03 (64 Mbit)
I (332) opi psram: good-die  : 0x01 (Pass)
I (337) opi psram: Latency   : 0x01 (Fixed)
I (341) opi psram: VCC       : 0x01 (3V)
I (346) opi psram: SRF       : 0x01 (Fast Refresh)
I (351) opi psram: BurstType : 0x01 (Hybrid Wrap)
I (357) opi psram: BurstLen  : 0x01 (32 Byte)
I (362) opi psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (368) opi psram: DriveStrength: 0x00 (1/1)
I (373) spiram: Found 64MBit SPI RAM device
I (378) spiram: SPI RAM mode: sram 80m
I (382) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (389) cpu_start: Pro cpu up.
I (393) cpu_start: Starting app cpu, entry point is 0x40376014
I (0) cpu_start: App cpu up.
I (694) spiram: SPI SRAM memory test OK
I (703) cpu_start: Pro cpu start user code
I (703) cpu_start: cpu freq: 240000000
I (704) cpu_start: Application information:
I (704) cpu_start: Project name:     esp32-s3-box-lite
I (705) cpu_start: App version:      2023.10.0b3
I (706) cpu_start: Compile time:     Oct 17 2023 19:41:22
I (706) cpu_start: ELF file SHA256:  2cd0a801a9403264...
I (707) cpu_start: ESP-IDF:          4.4.5
I (708) cpu_start: Min chip rev:     v0.0
I (708) cpu_start: Max chip rev:     v0.99 
I (709) cpu_start: Chip rev:         v0.1
I (709) heap_init: Initializing. RAM available for dynamic allocation:
I (710) heap_init: At 3FCA0498 len 00049278 (292 KiB): D/IRAM
I (711) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DIRAM
I (712) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (713) spiram: Adding pool of 8192K of external SPI memory to heap allocator
I (715) spi_flash: detected chip: gd
I (715) spi_flash: flash io: dio
I (716) sleep: Configure to isolate all GPIO pins in sleep state
I (717) sleep: Enable automatic switching of GPIO sleep configuration
I (718) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
[I][logger:271]: Log initialized
[C][ota:473]: There have been 8 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[D][ledc.output:055]: Calculating resolution bit-depth for frequency 1000.000000
[D][ledc.output:060]: Resolution calculated as 14
[I][esp_adf:019]: Start codec chip
[D][esp-idf:000]: I (142) gpio: GPIO[46]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 

[D][esp-idf:000]: W (144) I2C_BUS: i2c_bus_create:58: I2C bus has been already created, [port:0]

[D][esp-idf:000]: I (159) AUDIO_HAL: Codec mode is 3, Ctrl:1

[D][esp-idf:000]: I (162) gpio: GPIO[0]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 

[D][binary_sensor:034]: 'Left Top Button': Sending initial state OFF
[C][light:035]: Setting up light 'LCD Backlight'...
[D][light:036]: 'LCD Backlight' Setting:
[D][light:041]:   Color mode: 
[D][template.switch:046]:   Restored state ON
[D][switch:012]: 'Use wake word' Turning ON.
[D][switch:055]: 'Use wake word': Sending state ON
[E][voice_assistant:412]: No API client connected
[D][voice_assistant:366]: State changed from IDLE to IDLE
[D][voice_assistant:372]: Desired state set to IDLE
[W][light:176]: 'LCD Backlight' - This color mode does not support setting RGB color!
[D][light:036]: 'LCD Backlight' Setting:
[D][light:047]:   State: ON
[D][light:051]:   Brightness: 100%
[C][adc:047]: Setting up ADC 'front_buttons'...
[D][esp-idf:000]: I (171) gpio: GPIO[1]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 

[C][adc:093]: ADC 'front_buttons' setup finished!
[C][wifi:038]: Setting up WiFi...
[D][esp-idf:000]: I (175) pp: pp rom version: e7ae62f

[D][esp-idf:000]: I (176) net80211: net80211 rom version: e7ae62f

[D][esp-idf:000]: I (179) wifi:
[D][esp-idf:000]: wifi driver task: 3fcab434, prio:23, stack:6656, core=0
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1080) system_api: Base MAC address is not set

[D][esp-idf:000]: I (1081) system_api: read default base MAC address from EFUSE

[D][esp-idf:000]: I (1083) wifi:
[D][esp-idf:000]: wifi firmware version: 0f80fa0
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1084) wifi:
[D][esp-idf:000]: wifi certification version: v7.0
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1084) wifi:
[D][esp-idf:000]: config NVS flash: enabled
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1086) wifi:
[D][esp-idf:000]: config nano formating: disabled
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1087) wifi:
[D][esp-idf:000]: Init data frame dynamic rx buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1088) wifi:
[D][esp-idf:000]: Init management frame dynamic rx buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1089) wifi:
[D][esp-idf:000]: Init management short buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1090) wifi:
[D][esp-idf:000]: Init dynamic tx buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1092) wifi:
[D][esp-idf:000]: Init tx cache buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1093) wifi:
[D][esp-idf:000]: Init static tx FG buffer num: 2
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1095) wifi:
[D][esp-idf:000]: Init static rx buffer size: 1600
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1096) wifi:
[D][esp-idf:000]: Init static rx buffer num: 10
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1097) wifi:
[D][esp-idf:000]: Init dynamic rx buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1099) wifi_init: rx ba win: 6

[D][esp-idf:000]: I (1100) wifi_init: tcpip mbox: 32

[D][esp-idf:000]: I (1101) wifi_init: udp mbox: 6

[D][esp-idf:000]: I (1102) wifi_init: tcp mbox: 6

[D][esp-idf:000]: I (1103) wifi_init: tcp tx win: 5744

[D][esp-idf:000]: I (1103) wifi_init: tcp rx win: 5744

[D][esp-idf:000]: I (1104) wifi_init: tcp mss: 1440

[D][esp-idf:000]: I (1105) wifi_init: WiFi IRAM OP enabled

[D][esp-idf:000]: I (1106) wifi_init: WiFi RX IRAM OP enabled

[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: 7C:DF:A1:FF:39:C0
[D][esp-idf:000]: I (1108) phy_init: phy_version 601,fe52df4,May 10 2023,17:26:54

[D][esp-idf:000]: I (1141) wifi:
[D][esp-idf:000]: mode : softAP (7c:df:a1:ff:39:c1)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1143) wifi:
[D][esp-idf:000]: Total power save buffer number: 16
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1144) wifi:
[D][esp-idf:000]: Init max length of beacon: 752/752
[D][esp-idf:000]: 

[D][esp-idf:000]: I (1146) wifi:
[D][esp-idf:000]: Init max length of beacon: 752/752
[D][esp-idf:000]: 

[C][wifi:230]: Setting up AP...
[C][wifi:232]:   AP SSID: 'esp32-s3-box-lite'
[C][wifi:233]:   AP Password: ''
[D][esp-idf:000]: I (1150) wifi:
[D][esp-idf:000]: Total power save buffer number: 16
[D][esp-idf:000]: 

[C][wifi:242]:   IP Address: 192.168.4.1
[C][ota:097]: Over-The-Air Updates:
[C][ota:098]:   Address: esp32-s3-box-lite.local:3232
[W][ota:107]: Last Boot was an unhandled reset, will proceed to safe mode in 2 restarts
[C][api:025]: Setting up Home Assistant API server...
[C][voice_assistant:028]: Setting up Voice Assistant...
[C][esp_adf.speaker:024]: Setting up ESP ADF Speaker...
[I][app:062]: setup() finished successfully!
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 1 cached, 0 written, 0 failed
[D][binary_sensor:036]: 'Left': Sending state OFF
[D][binary_sensor:036]: 'Middle': Sending state OFF
[D][binary_sensor:036]: 'Right': Sending state OFF
[I][app:102]: ESPHome version 2023.10.0b3 compiled on Oct 18 2023, 18:23:54
[I][app:104]: Project esphome.voice-assistant version 1.0
[C][logger:361]: Logger:
[C][logger:362]:   Level: DEBUG
[C][logger:363]:   Log Baud Rate: 115200
[C][logger:365]:   Hardware UART: USB_SERIAL_JTAG
[C][logger:369]:   Level for 'sensor': INFO
[C][template.binary_sensor:028]: Template Binary Sensor 'Left'
[C][template.binary_sensor:028]: Template Binary Sensor 'Middle'
[C][template.binary_sensor:028]: Template Binary Sensor 'Right'
[C][ledc.output:164]: LEDC Output:
[C][ledc.output:165]:   Pin GPIO45
[C][ledc.output:166]:   LEDC Channel: 0
[C][ledc.output:167]:   PWM Frequency: 1000.0 Hz
[C][ledc.output:168]:   Bit depth: 14
[C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Left Top Button'
[C][gpio.binary_sensor:016]:   Pin: GPIO0
[C][light:103]: Light 'LCD Backlight'
[C][light:105]:   Default Transition Length: 0.0s
[C][light:106]:   Gamma Correct: 2.80
[C][template.switch:068]: Template Switch 'Use wake word'
[C][template.switch:091]:   Restore Mode: restore defaults to ON
[C][template.switch:057]:   Optimistic: YES
[C][adc:097]: ADC Sensor 'front_buttons'
[C][adc:097]:   Device Class: 'voltage'
[C][adc:097]:   State Class: 'measurement'
[C][adc:097]:   Unit of Measurement: 'V'
[C][adc:097]:   Accuracy Decimals: 2
[C][adc:107]:   Pin: GPIO1
[C][adc:122]:  Attenuation: 11db
[C][adc:142]:   Update Interval: 0.016s
[C][psram:020]: PSRAM:
[C][psram:021]:   Available: YES
[C][psram:024]:   Size: 8191 KB
[C][wifi:546]: WiFi:
[W][wifi_esp32:868]: esp_wifi_sta_get_ap_info failed: ESP_ERR_WIFI_CONN
[C][wifi:382]:   Local MAC: 7C:DF:A1:FF:39:C0
[W][wifi_esp32:878]: esp_wifi_sta_get_ap_info failed: ESP_ERR_WIFI_CONN
[C][wifi:383]:   SSID: [redacted]
[C][wifi:384]:   IP Address: 0.0.0.0
[C][wifi:386]:   BSSID: [redacted]
[C][wifi:387]:   Hostname: 'esp32-s3-box-lite'
[W][wifi_esp32:889]: esp_wifi_sta_get_ap_info failed: ESP_ERR_WIFI_CONN
[C][wifi:389]:   Signal strength: 0 dB ▂▄▆█
[C][wifi:393]:   Channel: 1
[C][wifi:394]:   Subnet: 255.255.255.0
[C][wifi:395]:   Gateway: 192.168.4.1
[C][wifi:396]:   DNS1: 0.0.0.0
[C][wifi:397]:   DNS2: 0.0.0.0
[C][mdns:115]: mDNS:
[C][mdns:116]:   Hostname: esp32-s3-box-lite
[C][ota:097]: Over-The-Air Updates:
[C][ota:098]:   Address: esp32-s3-box-lite.local:3232
[W][ota:107]: Last Boot was an unhandled reset, will proceed to safe mode in 2 restarts
[C][api:138]: API Server:
[C][api:139]:   Address: esp32-s3-box-lite.local:6053
[C][api:143]:   Using noise encryption: NO
[D][binary_sensor:036]: 'Left Top Button': Sending state ON
[D][binary_sensor:036]: 'Left Top Button': Sending state OFF
[W][light:176]: 'LCD Backlight' - This color mode does not support setting RGB color!
[D][light:036]: 'LCD Backlight' Setting:
[D][light:051]:   Brightness: 100%
[E][voice_assistant:412]: No API client connected
[D][voice_assistant:366]: State changed from IDLE to IDLE
Terminal disconnected: NetworkError: The device has been lost.

**Comment by bert269** [comment]
I used the same code as supplied on Github, with wifi credentials added, but it does not give any indication on the screen that it is working after the flash. It seems to go into a boot-loop, as I hear it connecting and dsconnection constantly form the USB-connection sound.
The default code does not prompt for the wifi credentials, on the box-lite.
I will try to flash one of the S3-boxes (non-lite) to see if that works better.
