### ISSUE TITLE
GL-S10 and other diy proxies aren't available on the install page anymore

### ISSUE THREAD

**Issue by blakadder** [esphome/firmware#93]
GL-S10 and other diy proxies aren't available on the install page anymore

**Comment by LeiChat** [comment]
Slightly off-topic, sorry. Noticed you had requested a photo of the new version of the GL-S10 on an issue in the old repository, so thought I would share here. I am using your web flasher but not sure which button to press to put the GL-S10 v2.1 into flashing mode.
![IMG20231129164302](https://github.com/esphome/firmware/assets/23559551/2625670d-801a-4276-80e4-be2c2c213a19)

**Comment by KSchmeeds** [comment]
I'm noticing this as well, it seems the advanced/DIY option is gone from the webpage.

**Comment by jesserockz** [comment]
Yes, we felt that they did not "fit" well with the aim of the new ready made projects page. 

We still build the firmware files, and a better place to have a page for flashing specific devices could potentially be on https://devices.esphome.io

**Comment by blakadder** [comment]
I've put up firmware for both versions of GL-S10 on https://blakadder.github.io/bluetooth-proxies/
